/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AttendanceIndexRouteImport } from './routes/attendance.index'
import { Route as AttendanceSemesterRouteImport } from './routes/attendance.$semester'
import { Route as ExpensesIndexRouteImport } from './routes/expenses.index'
import { Route as HabitsIndexRouteImport } from './routes/habits.index'
import { Route as HabitsHabitIdRouteImport } from './routes/habits.$habitId'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnRoadmapIdRouteImport } from './routes/learn.$roadmapId'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileBackupRouteImport } from './routes/profile.backup'
import { Route as ProfileModulesRouteImport } from './routes/profile.modules'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as LearnRoadmapIdTopicIdRouteImport } from './routes/learn.$roadmapId_.$topicId'
import { Route as NotesNoteIdEditRouteImport } from './routes/notes.$noteId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AttendanceRoute,
} as any)
const AttendanceSemesterRoute = AttendanceSemesterRouteImport.update({
  id: '/$semester',
  path: '/$semester',
  getParentRoute: () => AttendanceRoute,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpensesRoute,
} as any)
const HabitsIndexRoute = HabitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HabitsRoute,
} as any)
const HabitsHabitIdRoute = HabitsHabitIdRouteImport.update({
  id: '/$habitId',
  path: '/$habitId',
  getParentRoute: () => HabitsRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnRoadmapIdRoute = LearnRoadmapIdRouteImport.update({
  id: '/$roadmapId',
  path: '/$roadmapId',
  getParentRoute: () => LearnRoute,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesRoute,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => NotesRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileBackupRoute = ProfileBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileModulesRoute = ProfileModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProfileRoute,
} as any)
const LearnRoadmapIdTopicIdRoute = LearnRoadmapIdTopicIdRouteImport.update({
  id: '/$roadmapId_/$topicId',
  path: '/$roadmapId/$topicId',
  getParentRoute: () => LearnRoute,
} as any)
const NotesNoteIdEditRoute = NotesNoteIdEditRouteImport.update({
  id: '/$noteId_/edit',
  path: '/$noteId/edit',
  getParentRoute: () => NotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRouteWithChildren
  '/expenses': typeof ExpensesRouteWithChildren
  '/habits': typeof HabitsRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/notes': typeof NotesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/attendance/$semester': typeof AttendanceSemesterRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/learn/$roadmapId': typeof LearnRoadmapIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/profile/backup': typeof ProfileBackupRoute
  '/profile/modules': typeof ProfileModulesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/habits/': typeof HabitsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/learn/$roadmapId/$topicId': typeof LearnRoadmapIdTopicIdRoute
  '/notes/$noteId/edit': typeof NotesNoteIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/notifications': typeof NotificationsRoute
  '/planner': typeof PlannerRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/attendance/$semester': typeof AttendanceSemesterRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/learn/$roadmapId': typeof LearnRoadmapIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/profile/backup': typeof ProfileBackupRoute
  '/profile/modules': typeof ProfileModulesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/attendance': typeof AttendanceIndexRoute
  '/expenses': typeof ExpensesIndexRoute
  '/habits': typeof HabitsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/notes': typeof NotesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/learn/$roadmapId/$topicId': typeof LearnRoadmapIdTopicIdRoute
  '/notes/$noteId/edit': typeof NotesNoteIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRouteWithChildren
  '/expenses': typeof ExpensesRouteWithChildren
  '/habits': typeof HabitsRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/notes': typeof NotesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/attendance/$semester': typeof AttendanceSemesterRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/learn/$roadmapId': typeof LearnRoadmapIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/profile/backup': typeof ProfileBackupRoute
  '/profile/modules': typeof ProfileModulesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/habits/': typeof HabitsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/learn/$roadmapId_/$topicId': typeof LearnRoadmapIdTopicIdRoute
  '/notes/$noteId_/edit': typeof NotesNoteIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/attendance'
    | '/expenses'
    | '/habits'
    | '/learn'
    | '/notes'
    | '/notifications'
    | '/planner'
    | '/profile'
    | '/projects'
    | '/sitemap.xml'
    | '/attendance/$semester'
    | '/habits/$habitId'
    | '/learn/$roadmapId'
    | '/notes/$noteId'
    | '/profile/backup'
    | '/profile/modules'
    | '/profile/notifications'
    | '/attendance/'
    | '/expenses/'
    | '/habits/'
    | '/learn/'
    | '/notes/'
    | '/profile/'
    | '/learn/$roadmapId/$topicId'
    | '/notes/$noteId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/notifications'
    | '/planner'
    | '/projects'
    | '/sitemap.xml'
    | '/attendance/$semester'
    | '/habits/$habitId'
    | '/learn/$roadmapId'
    | '/notes/$noteId'
    | '/profile/backup'
    | '/profile/modules'
    | '/profile/notifications'
    | '/attendance'
    | '/expenses'
    | '/habits'
    | '/learn'
    | '/notes'
    | '/profile'
    | '/learn/$roadmapId/$topicId'
    | '/notes/$noteId/edit'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/attendance'
    | '/expenses'
    | '/habits'
    | '/learn'
    | '/notes'
    | '/notifications'
    | '/planner'
    | '/profile'
    | '/projects'
    | '/sitemap.xml'
    | '/attendance/$semester'
    | '/habits/$habitId'
    | '/learn/$roadmapId'
    | '/notes/$noteId'
    | '/profile/backup'
    | '/profile/modules'
    | '/profile/notifications'
    | '/attendance/'
    | '/expenses/'
    | '/habits/'
    | '/learn/'
    | '/notes/'
    | '/profile/'
    | '/learn/$roadmapId_/$topicId'
    | '/notes/$noteId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AttendanceRoute: typeof AttendanceRouteWithChildren
  ExpensesRoute: typeof ExpensesRouteWithChildren
  HabitsRoute: typeof HabitsRouteWithChildren
  LearnRoute: typeof LearnRouteWithChildren
  NotesRoute: typeof NotesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/attendance/$semester': {
      id: '/attendance/$semester'
      path: '/$semester'
      fullPath: '/attendance/$semester'
      preLoaderRoute: typeof AttendanceSemesterRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/habits/': {
      id: '/habits/'
      path: '/'
      fullPath: '/habits/'
      preLoaderRoute: typeof HabitsIndexRouteImport
      parentRoute: typeof HabitsRoute
    }
    '/habits/$habitId': {
      id: '/habits/$habitId'
      path: '/$habitId'
      fullPath: '/habits/$habitId'
      preLoaderRoute: typeof HabitsHabitIdRouteImport
      parentRoute: typeof HabitsRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$roadmapId': {
      id: '/learn/$roadmapId'
      path: '/$roadmapId'
      fullPath: '/learn/$roadmapId'
      preLoaderRoute: typeof LearnRoadmapIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof NotesRoute
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof NotesRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/backup': {
      id: '/profile/backup'
      path: '/backup'
      fullPath: '/profile/backup'
      preLoaderRoute: typeof ProfileBackupRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/modules': {
      id: '/profile/modules'
      path: '/modules'
      fullPath: '/profile/modules'
      preLoaderRoute: typeof ProfileModulesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/learn/$roadmapId_/$topicId': {
      id: '/learn/$roadmapId_/$topicId'
      path: '/$roadmapId/$topicId'
      fullPath: '/learn/$roadmapId/$topicId'
      preLoaderRoute: typeof LearnRoadmapIdTopicIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/notes/$noteId_/edit': {
      id: '/notes/$noteId_/edit'
      path: '/$noteId/edit'
      fullPath: '/notes/$noteId/edit'
      preLoaderRoute: typeof NotesNoteIdEditRouteImport
      parentRoute: typeof NotesRoute
    }
  }
}

interface AttendanceRouteChildren {
  AttendanceSemesterRoute: typeof AttendanceSemesterRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
}

const AttendanceRouteChildren: AttendanceRouteChildren = {
  AttendanceSemesterRoute: AttendanceSemesterRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
}

const AttendanceRouteWithChildren = AttendanceRoute._addFileChildren(
  AttendanceRouteChildren,
)

interface ExpensesRouteChildren {
  ExpensesIndexRoute: typeof ExpensesIndexRoute
}

const ExpensesRouteChildren: ExpensesRouteChildren = {
  ExpensesIndexRoute: ExpensesIndexRoute,
}

const ExpensesRouteWithChildren = ExpensesRoute._addFileChildren(
  ExpensesRouteChildren,
)

interface HabitsRouteChildren {
  HabitsHabitIdRoute: typeof HabitsHabitIdRoute
  HabitsIndexRoute: typeof HabitsIndexRoute
}

const HabitsRouteChildren: HabitsRouteChildren = {
  HabitsHabitIdRoute: HabitsHabitIdRoute,
  HabitsIndexRoute: HabitsIndexRoute,
}

const HabitsRouteWithChildren =
  HabitsRoute._addFileChildren(HabitsRouteChildren)

interface LearnRouteChildren {
  LearnRoadmapIdRoute: typeof LearnRoadmapIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LearnRoadmapIdTopicIdRoute: typeof LearnRoadmapIdTopicIdRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnRoadmapIdRoute: LearnRoadmapIdRoute,
  LearnIndexRoute: LearnIndexRoute,
  LearnRoadmapIdTopicIdRoute: LearnRoadmapIdTopicIdRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface NotesRouteChildren {
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  NotesIndexRoute: typeof NotesIndexRoute
  NotesNoteIdEditRoute: typeof NotesNoteIdEditRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesNoteIdRoute: NotesNoteIdRoute,
  NotesIndexRoute: NotesIndexRoute,
  NotesNoteIdEditRoute: NotesNoteIdEditRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface ProfileRouteChildren {
  ProfileBackupRoute: typeof ProfileBackupRoute
  ProfileModulesRoute: typeof ProfileModulesRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileBackupRoute: ProfileBackupRoute,
  ProfileModulesRoute: ProfileModulesRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AttendanceRoute: AttendanceRouteWithChildren,
  ExpensesRoute: ExpensesRouteWithChildren,
  HabitsRoute: HabitsRouteWithChildren,
  LearnRoute: LearnRouteWithChildren,
  NotesRoute: NotesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
