/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CodingRouteImport } from './routes/coding'
import { Route as CgpaRouteImport } from './routes/cgpa'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as HabitsIndexRouteImport } from './routes/habits.index'
import { Route as ExpensesIndexRouteImport } from './routes/expenses.index'
import { Route as CodingIndexRouteImport } from './routes/coding.index'
import { Route as CareerIndexRouteImport } from './routes/career.index'
import { Route as AttendanceIndexRouteImport } from './routes/attendance.index'
import { Route as ProfileSystemRouteImport } from './routes/profile.system'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as ProfileModulesRouteImport } from './routes/profile.modules'
import { Route as ProfileBackupRouteImport } from './routes/profile.backup'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as LearnRoadmapIdRouteImport } from './routes/learn.$roadmapId'
import { Route as HabitsHabitIdRouteImport } from './routes/habits.$habitId'
import { Route as AttendanceSemesterRouteImport } from './routes/attendance.$semester'
import { Route as NotesNoteIdEditRouteImport } from './routes/notes.$noteId_.edit'
import { Route as LearnRoadmapIdTopicIdRouteImport } from './routes/learn.$roadmapId_.$topicId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingRoute = CodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => rootRouteImport,
} as any)
const CgpaRoute = CgpaRouteImport.update({
  id: '/cgpa',
  path: '/cgpa',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const HabitsIndexRoute = HabitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HabitsRoute,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpensesRoute,
} as any)
const CodingIndexRoute = CodingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CodingRoute,
} as any)
const CareerIndexRoute = CareerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareerRoute,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AttendanceRoute,
} as any)
const ProfileSystemRoute = ProfileSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileModulesRoute = ProfileModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileBackupRoute = ProfileBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => ProfileRoute,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => NotesRoute,
} as any)
const LearnRoadmapIdRoute = LearnRoadmapIdRouteImport.update({
  id: '/$roadmapId',
  path: '/$roadmapId',
  getParentRoute: () => LearnRoute,
} as any)
const HabitsHabitIdRoute = HabitsHabitIdRouteImport.update({
  id: '/$habitId',
  path: '/$habitId',
  getParentRoute: () => HabitsRoute,
} as any)
const AttendanceSemesterRoute = AttendanceSemesterRouteImport.update({
  id: '/$semester',
  path: '/$semester',
  getParentRoute: () => AttendanceRoute,
} as any)
const NotesNoteIdEditRoute = NotesNoteIdEditRouteImport.update({
  id: '/$noteId_/edit',
  path: '/$noteId/edit',
  getParentRoute: () => NotesRoute,
} as any)
const LearnRoadmapIdTopicIdRoute = LearnRoadmapIdTopicIdRouteImport.update({
  id: '/$roadmapId_/$topicId',
  path: '/$roadmapId/$topicId',
  getParentRoute: () => LearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRouteWithChildren
  '/career': typeof CareerRouteWithChildren
  '/cgpa': typeof CgpaRoute
  '/coding': typeof CodingRouteWithChildren
  '/expenses': typeof ExpensesRouteWithChildren
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/notes': typeof NotesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/attendance/$semester': typeof AttendanceSemesterRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/learn/$roadmapId': typeof LearnRoadmapIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/profile/backup': typeof ProfileBackupRoute
  '/profile/modules': typeof ProfileModulesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/system': typeof ProfileSystemRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/career/': typeof CareerIndexRoute
  '/coding/': typeof CodingIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/habits/': typeof HabitsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/learn/$roadmapId/$topicId': typeof LearnRoadmapIdTopicIdRoute
  '/notes/$noteId/edit': typeof NotesNoteIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/cgpa': typeof CgpaRoute
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/notifications': typeof NotificationsRoute
  '/planner': typeof PlannerRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/attendance/$semester': typeof AttendanceSemesterRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/learn/$roadmapId': typeof LearnRoadmapIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/profile/backup': typeof ProfileBackupRoute
  '/profile/modules': typeof ProfileModulesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/system': typeof ProfileSystemRoute
  '/attendance': typeof AttendanceIndexRoute
  '/career': typeof CareerIndexRoute
  '/coding': typeof CodingIndexRoute
  '/expenses': typeof ExpensesIndexRoute
  '/habits': typeof HabitsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/notes': typeof NotesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/learn/$roadmapId/$topicId': typeof LearnRoadmapIdTopicIdRoute
  '/notes/$noteId/edit': typeof NotesNoteIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRouteWithChildren
  '/career': typeof CareerRouteWithChildren
  '/cgpa': typeof CgpaRoute
  '/coding': typeof CodingRouteWithChildren
  '/expenses': typeof ExpensesRouteWithChildren
  '/focus': typeof FocusRoute
  '/goals': typeof GoalsRoute
  '/habits': typeof HabitsRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/notes': typeof NotesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/attendance/$semester': typeof AttendanceSemesterRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/learn/$roadmapId': typeof LearnRoadmapIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/profile/backup': typeof ProfileBackupRoute
  '/profile/modules': typeof ProfileModulesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/system': typeof ProfileSystemRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/career/': typeof CareerIndexRoute
  '/coding/': typeof CodingIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/habits/': typeof HabitsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/learn/$roadmapId_/$topicId': typeof LearnRoadmapIdTopicIdRoute
  '/notes/$noteId_/edit': typeof NotesNoteIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/attendance'
    | '/career'
    | '/cgpa'
    | '/coding'
    | '/expenses'
    | '/focus'
    | '/goals'
    | '/habits'
    | '/learn'
    | '/notes'
    | '/notifications'
    | '/planner'
    | '/profile'
    | '/projects'
    | '/resume'
    | '/review'
    | '/search'
    | '/sitemap.xml'
    | '/attendance/$semester'
    | '/habits/$habitId'
    | '/learn/$roadmapId'
    | '/notes/$noteId'
    | '/profile/backup'
    | '/profile/modules'
    | '/profile/notifications'
    | '/profile/system'
    | '/attendance/'
    | '/career/'
    | '/coding/'
    | '/expenses/'
    | '/habits/'
    | '/learn/'
    | '/notes/'
    | '/profile/'
    | '/learn/$roadmapId/$topicId'
    | '/notes/$noteId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/cgpa'
    | '/focus'
    | '/goals'
    | '/notifications'
    | '/planner'
    | '/projects'
    | '/resume'
    | '/review'
    | '/search'
    | '/sitemap.xml'
    | '/attendance/$semester'
    | '/habits/$habitId'
    | '/learn/$roadmapId'
    | '/notes/$noteId'
    | '/profile/backup'
    | '/profile/modules'
    | '/profile/notifications'
    | '/profile/system'
    | '/attendance'
    | '/career'
    | '/coding'
    | '/expenses'
    | '/habits'
    | '/learn'
    | '/notes'
    | '/profile'
    | '/learn/$roadmapId/$topicId'
    | '/notes/$noteId/edit'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/attendance'
    | '/career'
    | '/cgpa'
    | '/coding'
    | '/expenses'
    | '/focus'
    | '/goals'
    | '/habits'
    | '/learn'
    | '/notes'
    | '/notifications'
    | '/planner'
    | '/profile'
    | '/projects'
    | '/resume'
    | '/review'
    | '/search'
    | '/sitemap.xml'
    | '/attendance/$semester'
    | '/habits/$habitId'
    | '/learn/$roadmapId'
    | '/notes/$noteId'
    | '/profile/backup'
    | '/profile/modules'
    | '/profile/notifications'
    | '/profile/system'
    | '/attendance/'
    | '/career/'
    | '/coding/'
    | '/expenses/'
    | '/habits/'
    | '/learn/'
    | '/notes/'
    | '/profile/'
    | '/learn/$roadmapId_/$topicId'
    | '/notes/$noteId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AttendanceRoute: typeof AttendanceRouteWithChildren
  CareerRoute: typeof CareerRouteWithChildren
  CgpaRoute: typeof CgpaRoute
  CodingRoute: typeof CodingRouteWithChildren
  ExpensesRoute: typeof ExpensesRouteWithChildren
  FocusRoute: typeof FocusRoute
  GoalsRoute: typeof GoalsRoute
  HabitsRoute: typeof HabitsRouteWithChildren
  LearnRoute: typeof LearnRouteWithChildren
  NotesRoute: typeof NotesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  ResumeRoute: typeof ResumeRoute
  ReviewRoute: typeof ReviewRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding': {
      id: '/coding'
      path: '/coding'
      fullPath: '/coding'
      preLoaderRoute: typeof CodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgpa': {
      id: '/cgpa'
      path: '/cgpa'
      fullPath: '/cgpa'
      preLoaderRoute: typeof CgpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof NotesRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/habits/': {
      id: '/habits/'
      path: '/'
      fullPath: '/habits/'
      preLoaderRoute: typeof HabitsIndexRouteImport
      parentRoute: typeof HabitsRoute
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/coding/': {
      id: '/coding/'
      path: '/'
      fullPath: '/coding/'
      preLoaderRoute: typeof CodingIndexRouteImport
      parentRoute: typeof CodingRoute
    }
    '/career/': {
      id: '/career/'
      path: '/'
      fullPath: '/career/'
      preLoaderRoute: typeof CareerIndexRouteImport
      parentRoute: typeof CareerRoute
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/profile/system': {
      id: '/profile/system'
      path: '/system'
      fullPath: '/profile/system'
      preLoaderRoute: typeof ProfileSystemRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/modules': {
      id: '/profile/modules'
      path: '/modules'
      fullPath: '/profile/modules'
      preLoaderRoute: typeof ProfileModulesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/backup': {
      id: '/profile/backup'
      path: '/backup'
      fullPath: '/profile/backup'
      preLoaderRoute: typeof ProfileBackupRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof NotesRoute
    }
    '/learn/$roadmapId': {
      id: '/learn/$roadmapId'
      path: '/$roadmapId'
      fullPath: '/learn/$roadmapId'
      preLoaderRoute: typeof LearnRoadmapIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/habits/$habitId': {
      id: '/habits/$habitId'
      path: '/$habitId'
      fullPath: '/habits/$habitId'
      preLoaderRoute: typeof HabitsHabitIdRouteImport
      parentRoute: typeof HabitsRoute
    }
    '/attendance/$semester': {
      id: '/attendance/$semester'
      path: '/$semester'
      fullPath: '/attendance/$semester'
      preLoaderRoute: typeof AttendanceSemesterRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/notes/$noteId_/edit': {
      id: '/notes/$noteId_/edit'
      path: '/$noteId/edit'
      fullPath: '/notes/$noteId/edit'
      preLoaderRoute: typeof NotesNoteIdEditRouteImport
      parentRoute: typeof NotesRoute
    }
    '/learn/$roadmapId_/$topicId': {
      id: '/learn/$roadmapId_/$topicId'
      path: '/$roadmapId/$topicId'
      fullPath: '/learn/$roadmapId/$topicId'
      preLoaderRoute: typeof LearnRoadmapIdTopicIdRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface AttendanceRouteChildren {
  AttendanceSemesterRoute: typeof AttendanceSemesterRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
}

const AttendanceRouteChildren: AttendanceRouteChildren = {
  AttendanceSemesterRoute: AttendanceSemesterRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
}

const AttendanceRouteWithChildren = AttendanceRoute._addFileChildren(
  AttendanceRouteChildren,
)

interface CareerRouteChildren {
  CareerIndexRoute: typeof CareerIndexRoute
}

const CareerRouteChildren: CareerRouteChildren = {
  CareerIndexRoute: CareerIndexRoute,
}

const CareerRouteWithChildren =
  CareerRoute._addFileChildren(CareerRouteChildren)

interface CodingRouteChildren {
  CodingIndexRoute: typeof CodingIndexRoute
}

const CodingRouteChildren: CodingRouteChildren = {
  CodingIndexRoute: CodingIndexRoute,
}

const CodingRouteWithChildren =
  CodingRoute._addFileChildren(CodingRouteChildren)

interface ExpensesRouteChildren {
  ExpensesIndexRoute: typeof ExpensesIndexRoute
}

const ExpensesRouteChildren: ExpensesRouteChildren = {
  ExpensesIndexRoute: ExpensesIndexRoute,
}

const ExpensesRouteWithChildren = ExpensesRoute._addFileChildren(
  ExpensesRouteChildren,
)

interface HabitsRouteChildren {
  HabitsHabitIdRoute: typeof HabitsHabitIdRoute
  HabitsIndexRoute: typeof HabitsIndexRoute
}

const HabitsRouteChildren: HabitsRouteChildren = {
  HabitsHabitIdRoute: HabitsHabitIdRoute,
  HabitsIndexRoute: HabitsIndexRoute,
}

const HabitsRouteWithChildren =
  HabitsRoute._addFileChildren(HabitsRouteChildren)

interface LearnRouteChildren {
  LearnRoadmapIdRoute: typeof LearnRoadmapIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LearnRoadmapIdTopicIdRoute: typeof LearnRoadmapIdTopicIdRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnRoadmapIdRoute: LearnRoadmapIdRoute,
  LearnIndexRoute: LearnIndexRoute,
  LearnRoadmapIdTopicIdRoute: LearnRoadmapIdTopicIdRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface NotesRouteChildren {
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  NotesIndexRoute: typeof NotesIndexRoute
  NotesNoteIdEditRoute: typeof NotesNoteIdEditRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesNoteIdRoute: NotesNoteIdRoute,
  NotesIndexRoute: NotesIndexRoute,
  NotesNoteIdEditRoute: NotesNoteIdEditRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface ProfileRouteChildren {
  ProfileBackupRoute: typeof ProfileBackupRoute
  ProfileModulesRoute: typeof ProfileModulesRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfileSystemRoute: typeof ProfileSystemRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileBackupRoute: ProfileBackupRoute,
  ProfileModulesRoute: ProfileModulesRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfileSystemRoute: ProfileSystemRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AttendanceRoute: AttendanceRouteWithChildren,
  CareerRoute: CareerRouteWithChildren,
  CgpaRoute: CgpaRoute,
  CodingRoute: CodingRouteWithChildren,
  ExpensesRoute: ExpensesRouteWithChildren,
  FocusRoute: FocusRoute,
  GoalsRoute: GoalsRoute,
  HabitsRoute: HabitsRouteWithChildren,
  LearnRoute: LearnRouteWithChildren,
  NotesRoute: NotesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  ResumeRoute: ResumeRoute,
  ReviewRoute: ReviewRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
